services:

  postgres:
    image: postgres:16
    container_name: parkease-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AnaPassword
      POSTGRES_DB: parkease_auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - parkease-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: parkease-auth
    restart: always
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5001
      ConnectionStrings__AuthDb: Host=postgres;Port=5432;Database=parkease_auth_db;Username=postgres;Password=AnaPassword
      JwtSettings__SecretKey: ParkEase@SuperSecretKey#2026!MustBeAtLeast32Chars
      JwtSettings__Issuer: ParkEase.Auth
      JwtSettings__Audience: ParkEase.Client
      JwtSettings__AccessTokenExpiryMinutes: 60
      JwtSettings__RefreshTokenExpiryDays: 7
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parkease-network

  parkinglot-service:
    build:
      context: ./services/parkinglot-service
      dockerfile: Dockerfile
    container_name: parkease-parkinglot
    restart: always
    ports:
      - "5002:5002"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5002
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=parkease_parkinglot_db;Username=postgres;Password=AnaPassword
      JwtSettings__SecretKey: ParkEase@SuperSecretKey#2026!MustBeAtLeast32Chars
      JwtSettings__Issuer: ParkEase.Auth
      JwtSettings__Audience: ParkEase.Client
      JwtSettings__AccessTokenExpiryMinutes: 60
      JwtSettings__RefreshTokenExpiryDays: 7
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parkease-network

  spot-service:
    build:
      context: ./services/spot-service
      dockerfile: Dockerfile
    container_name: parkease-spot
    restart: always
    ports:
      - "5003:5003"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5003
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=parkease_spot_db;Username=postgres;Password=AnaPassword
      JwtSettings__SecretKey: ParkEase@SuperSecretKey#2026!MustBeAtLeast32Chars
      JwtSettings__Issuer: ParkEase.Auth
      JwtSettings__Audience: ParkEase.Client
      JwtSettings__AccessTokenExpiryMinutes: 60
      JwtSettings__RefreshTokenExpiryDays: 7
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parkease-network

  booking-service:
    build:
      context: ./services/booking-service
      dockerfile: Dockerfile
    container_name: parkease-booking
    restart: always
    ports:
      - "5004:5004"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5004
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=parkease_booking_db;Username=postgres;Password=AnaPassword
      Services__SpotUrl: http://spot-service:5003
      Services__ParkingLotUrl: http://parkinglot-service:5002
      JwtSettings__SecretKey: ParkEase@SuperSecretKey#2026!MustBeAtLeast32Chars
      JwtSettings__Issuer: ParkEase.Auth
      JwtSettings__Audience: ParkEase.Client
      JwtSettings__AccessTokenExpiryMinutes: 60
      JwtSettings__RefreshTokenExpiryDays: 7
    depends_on:
      postgres:
        condition: service_healthy
      parkinglot-service:
        condition: service_started
      spot-service:
        condition: service_started
    networks:
      - parkease-network

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: parkease-payment
    restart: always
    ports:
      - "5005:5005"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5005
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=parkease_payment_db;Username=postgres;Password=AnaPassword
      JwtSettings__SecretKey: ParkEase@SuperSecretKey#2026!MustBeAtLeast32Chars
      JwtSettings__Issuer: ParkEase.Auth
      JwtSettings__Audience: ParkEase.Client
      JwtSettings__AccessTokenExpiryMinutes: 60
      JwtSettings__RefreshTokenExpiryDays: 7
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parkease-network

  vehicle-service:
    build:
      context: ./services/vehicle-service
      dockerfile: Dockerfile
    container_name: parkease-vehicle
    restart: always
    ports:
      - "5006:5006"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5006
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=parkease_vehicle_db;Username=postgres;Password=AnaPassword
      JwtSettings__SecretKey: ParkEase@SuperSecretKey#2026!MustBeAtLeast32Chars
      JwtSettings__Issuer: ParkEase.Auth
      JwtSettings__Audience: ParkEase.Client
      JwtSettings__AccessTokenExpiryMinutes: 60
      JwtSettings__RefreshTokenExpiryDays: 7
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parkease-network
volumes:
  postgres_data:

networks:
  parkease-network:
    driver: bridge
