using Microsoft.EntityFrameworkCore;
using ParkingLotEntity = ParkingLot.Domain.Entities.ParkingLot;

namespace ParkingLot.Infrastructure.Persistence.Seed;

public static class ParkingLotSeeder
{
    public static async Task SeedAsync(ParkingLotDbContext context)
    {
        await EnsureSchemaAsync(context);

        var lots = new List<ParkingLotEntity>
        {
            new()
            {
                Name = "ParkEase Central Plaza",
                Description = "Covered parking near Connaught Place with EV bays.",
                Address = "Block A, Connaught Place",
                City = "New Delhi",
                State = "Delhi",
                Pincode = "110001",
                Latitude = 28.6315,
                Longitude = 77.2167,
                TotalSpots = 10,
                AvailableSpots = 8,
                IsActive = true,
                IsApproved = true,
                IsOpen = true,
                ManagerId = 2,
                OpenTime = new TimeSpan(6, 0, 0),
                CloseTime = new TimeSpan(23, 0, 0),
                CreatedAt = DateTime.UtcNow
            },
            new()
            {
                Name = "ParkEase Cyber Hub",
                Description = "Multi-level parking for office commuters in Gurugram.",
                Address = "DLF Cyber City, Phase 2",
                City = "Gurugram",
                State = "Haryana",
                Pincode = "122002",
                Latitude = 28.4946,
                Longitude = 77.0889,
                TotalSpots = 8,
                AvailableSpots = 8,
                IsActive = true,
                IsApproved = true,
                IsOpen = true,
                ManagerId = 2,
                OpenTime = new TimeSpan(7, 0, 0),
                CloseTime = new TimeSpan(22, 0, 0),
                CreatedAt = DateTime.UtcNow
            }
        };

        foreach (var lot in lots)
        {
            var exists = await context.ParkingLots
                .AnyAsync(x => x.Name == lot.Name && x.City == lot.City);

            if (!exists)
                await context.ParkingLots.AddAsync(lot);
        }

        await context.SaveChangesAsync();
    }

    private static Task EnsureSchemaAsync(ParkingLotDbContext context)
    {
        return context.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ParkingLots" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Name" character varying(100) NOT NULL,
                "Description" character varying(500) NOT NULL,
                "Address" character varying(200) NOT NULL,
                "City" character varying(100) NOT NULL,
                "State" character varying(100) NOT NULL,
                "Pincode" character varying(20) NOT NULL,
                "Latitude" double precision NOT NULL,
                "Longitude" double precision NOT NULL,
                "TotalSpots" integer NOT NULL,
                "AvailableSpots" integer NOT NULL,
                "IsActive" boolean NOT NULL,
                "IsApproved" boolean NOT NULL,
                "IsOpen" boolean NOT NULL,
                "ManagerId" integer NOT NULL,
                "OpenTime" interval NOT NULL,
                "CloseTime" interval NOT NULL,
                "ImageUrl" text NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NULL,
                CONSTRAINT "PK_ParkingLots" PRIMARY KEY ("Id")
            );
            """);
    }
}
