using Microsoft.EntityFrameworkCore;
using ParkEase.Spot.Domain.Enums;
using SpotEntity = ParkEase.Spot.Domain.Entities.Spot;

namespace ParkEase.Spot.Infrastructure.Persistence.Seed;

public static class SpotSeeder
{
    public static async Task SeedAsync(SpotDbContext context)
    {
        await EnsureSchemaAsync(context);

        var spots = new List<SpotEntity>
        {
            new SpotEntity
            {
                LotId = 1,
                SpotNumber = "A-01",
                Floor = 0,
                SpotType = SpotType.Standard,
                VehicleType = VehicleType.FourWheeler,
                Status = SpotStatus.Available,
                PricePerHour = 40,
                CreatedAt = DateTime.UtcNow
            },
            new SpotEntity()
            {
                LotId = 1,
                SpotNumber = "A-02",
                Floor = 0,
                SpotType = SpotType.EV,
                VehicleType = VehicleType.FourWheeler,
                Status = SpotStatus.Occupied,
                IsEVCharging = true,
                PricePerHour = 60,
                CreatedAt = DateTime.UtcNow
            },
            new SpotEntity()
            {
                LotId = 1,
                SpotNumber = "A-03",
                Floor = 0,
                SpotType = SpotType.Standard,
                VehicleType = VehicleType.FourWheeler,
                Status = SpotStatus.Available,
                PricePerHour = 40,
                CreatedAt = DateTime.UtcNow
            },
            new SpotEntity()
            {
                LotId = 1,
                SpotNumber = "B-01",
                Floor = 1,
                SpotType = SpotType.Compact,
                VehicleType = VehicleType.TwoWheeler,
                Status = SpotStatus.Available,
                PricePerHour = 20,
                CreatedAt = DateTime.UtcNow
            },
            new SpotEntity()
            {
                LotId = 1,
                SpotNumber = "B-02",
                Floor = 1,
                SpotType = SpotType.Large,
                VehicleType = VehicleType.Heavy,
                Status = SpotStatus.Available,
                PricePerHour = 80,
                CreatedAt = DateTime.UtcNow
            },
            new SpotEntity()
            {
                LotId = 2,
                SpotNumber = "C-01",
                Floor = 0,
                SpotType = SpotType.Standard,
                VehicleType = VehicleType.FourWheeler,
                Status = SpotStatus.Available,
                PricePerHour = 50,
                CreatedAt = DateTime.UtcNow
            },
            new SpotEntity()
            {
                LotId = 2,
                SpotNumber = "C-02",
                Floor = 0,
                SpotType = SpotType.Standard,
                VehicleType = VehicleType.FourWheeler,
                Status = SpotStatus.Available,
                PricePerHour = 50,
                CreatedAt = DateTime.UtcNow
            }
        };

        foreach (var spot in spots)
        {
            var exists = await context.Spots
                .AnyAsync(x => x.LotId == spot.LotId && x.SpotNumber == spot.SpotNumber);

            if (!exists)
                await context.Spots.AddAsync(spot);
        }

        await context.SaveChangesAsync();
    }

    private static Task EnsureSchemaAsync(SpotDbContext context)
    {
        return context.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Spots" (
                "SpotId" integer GENERATED BY DEFAULT AS IDENTITY,
                "LotId" integer NOT NULL,
                "SpotNumber" character varying(50) NOT NULL,
                "Floor" integer NOT NULL,
                "SpotType" integer NOT NULL,
                "VehicleType" integer NOT NULL,
                "Status" integer NOT NULL,
                "IsHandicapped" boolean NOT NULL,
                "IsEVCharging" boolean NOT NULL,
                "PricePerHour" numeric(18,2) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_Spots" PRIMARY KEY ("SpotId")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Spots_LotId_SpotNumber"
                ON "Spots" ("LotId", "SpotNumber");
            """);
    }
}
